"""Import axis-baked v039 at positive scale into a fresh isolated Unreal review map."""
import hashlib,json
from datetime import datetime,timezone
from pathlib import Path
import unreal
ROOT=Path(unreal.Paths.project_dir());SOURCE=ROOT/"SourceAssets/Candidate/PressTrains/TrainA/UnrealAxisBaked_v039/FBX/SM_CA_MW_PressTrainA_UnrealAxisBaked_v039.fbx";SOURCE_SHA="70C7A21B33DDB5EF243740A6866B41C303CC62D0705CE9A1F839A2DA0411674E";DEST="/Game/LineBoss/Candidates/PressTrains/TrainA/AxisBaked_v325";ASSET=DEST+"/SM_CA_MW_PressTrainA_UnrealAxisBaked_v039";MAP="/Game/LineBoss/Maps/LB_PressTrainA_AxisBakedReviewCandidate_v325";MAP_FILE=ROOT/"Content/LineBoss/Maps/LB_PressTrainA_AxisBakedReviewCandidate_v325.umap";OUT=ROOT/"Saved/Audits/PressTrains/press_train_a_axis_baked_unreal_intake_build_v325.json";lib=unreal.EditorAssetLibrary;levels=unreal.get_editor_subsystem(unreal.LevelEditorSubsystem);api=unreal.get_editor_subsystem(unreal.EditorActorSubsystem)
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest().upper()
if sha(SOURCE)!=SOURCE_SHA:raise RuntimeError("v039 FBX hash drift")
if lib.does_directory_exist(DEST) or lib.does_asset_exist(MAP) or OUT.exists():raise RuntimeError("refusing to overwrite v325")
task=unreal.AssetImportTask();task.set_editor_properties({"filename":str(SOURCE),"destination_path":DEST,"destination_name":"SM_CA_MW_PressTrainA_UnrealAxisBaked_v039","automated":True,"replace_existing":False,"save":True});opts=unreal.FbxImportUI();opts.set_editor_properties({"import_mesh":True,"import_as_skeletal":False,"import_materials":True,"import_textures":False,"mesh_type_to_import":unreal.FBXImportType.FBXIT_STATIC_MESH});data=opts.get_editor_property("static_mesh_import_data");data.set_editor_properties({"combine_meshes":True,"convert_scene":True,"convert_scene_unit":True,"transform_vertex_to_absolute":False,"bake_pivot_in_vertex":False,"generate_lightmap_u_vs":True,"auto_generate_collision":False,"remove_degenerates":True});task.set_editor_property("options",opts);unreal.AssetToolsHelpers.get_asset_tools().import_asset_tasks([task]);unreal.AutomationUtilsBlueprintLibrary.finish_all_asset_compilation();mesh=lib.load_asset(ASSET)
if not isinstance(mesh,unreal.StaticMesh):raise RuntimeError("v325 mesh import missing")
if not levels.new_level(MAP):raise RuntimeError("new v325 studio level failed")
candidate=api.spawn_actor_from_class(unreal.StaticMeshActor,unreal.Vector(),unreal.Rotator());candidate.static_mesh_component.set_static_mesh(mesh);candidate.set_actor_label("CA_MW_PTA_AxisBaked_v039_STUDIO_VISUAL_ONLY_v325");candidate.set_actor_scale3d(unreal.Vector(100,100,100));candidate.tags=[unreal.Name(x) for x in ("LB.PressTrain.TrainA.AxisBakedSource.v039","LB.Review.IsolatedStudio.v325","LB.Collision.NoCollision","LB.Asset.CandidateNotPromoted")];candidate.static_mesh_component.set_collision_profile_name("NoCollision");candidate.static_mesh_component.set_editor_property("can_ever_affect_navigation",False);origin,extent=candidate.get_actor_bounds(False);candidate.add_actor_world_offset(unreal.Vector(0,0,-(origin.z-extent.z)),False,False);origin,extent=candidate.get_actor_bounds(False)
cube=lib.load_asset("/Engine/BasicShapes/Cube.Cube");floor=api.spawn_actor_from_class(unreal.StaticMeshActor,unreal.Vector(origin.x,origin.y,-12.5),unreal.Rotator());floor.static_mesh_component.set_static_mesh(cube);floor.set_actor_label("LB_V325_STUDIO_FLOOR");floor.set_actor_scale3d(unreal.Vector(max(60,extent.x/50+10),max(22,extent.y/50+10),0.25))
for i,x in enumerate((origin.x-2200,origin.x-750,origin.x+750,origin.x+2200),1):
 for side,y in (("front",origin.y-950),("rear",origin.y+950)):
  light=api.spawn_actor_from_class(unreal.PointLight,unreal.Vector(x,y,origin.z+620),unreal.Rotator());light.set_actor_label(f"LB_V325_MOVABLE_{side.upper()}_{i:02d}");light.point_light_component.set_mobility(unreal.ComponentMobility.MOVABLE);light.point_light_component.set_editor_properties({"intensity":85000.0,"attenuation_radius":3000.0,"cast_shadows":False})
def cam(label,loc,target):
 c=api.spawn_actor_from_class(unreal.CameraActor,unreal.Vector(*loc),unreal.Rotator());c.set_actor_label(label);c.set_actor_rotation(unreal.MathLibrary.find_look_at_rotation(c.get_actor_location(),unreal.Vector(*target)),False);c.camera_component.set_editor_properties({"projection_mode":unreal.CameraProjectionMode.ORTHOGRAPHIC,"ortho_width":max(6200.0,extent.x*2.2),"aspect_ratio":16/9,"constrain_aspect_ratio":True});s=c.camera_component.get_editor_property("post_process_settings");s.set_editor_properties({"override_auto_exposure_method":True,"auto_exposure_method":unreal.AutoExposureMethod.AEM_BASIC,"override_auto_exposure_min_brightness":True,"override_auto_exposure_max_brightness":True,"auto_exposure_min_brightness":1.0,"auto_exposure_max_brightness":1.0,"override_auto_exposure_bias":True,"auto_exposure_bias":3.5});c.camera_component.set_editor_property("post_process_settings",s);c.camera_component.set_editor_property("post_process_blend_weight",1.0)
target=(origin.x,origin.y,origin.z);cam("LB_V325_CAM_FACE_A",(origin.x,origin.y-2000,origin.z),target);cam("LB_V325_CAM_FACE_B",(origin.x,origin.y+2000,origin.z),target)
fail=[];size=[extent.x*2,extent.y*2,extent.z*2]
if abs(origin.z-extent.z)>1:fail.append("floor placement")
if min(size)<=0:fail.append("invalid bounds")
if not levels.save_current_level():fail.append("save failed")
payload={"$schema":"cairnwell/audit/press-train-a-axis-baked-unreal-intake-v325/v1","generated_utc":datetime.now(timezone.utc).isoformat(),"status":"PASS__AXIS_BAKED_POSITIVE_SCALE_VISUAL_GATE_READY__NOT_PROMOTED" if not fail else "FAIL__V325_NOT_EVIDENCE","source_fbx_sha256":SOURCE_SHA,"asset":ASSET,"map":MAP,"map_sha256":sha(MAP_FILE) if MAP_FILE.exists() else None,"candidate_scale":[100,100,100],"candidate_rotation":[0,0,0],"candidate_origin":[origin.x,origin.y,origin.z],"candidate_size_cm":size,"candidate_floor_z":origin.z-extent.z,"collision":"NoCollision","runtime_authority":None,"promotion_authorized":False,"failures":fail};OUT.parent.mkdir(parents=True,exist_ok=True);OUT.write_text(json.dumps(payload,indent=2),encoding="utf-8");print(json.dumps(payload,indent=2))
if fail:raise RuntimeError("; ".join(fail))
unreal.SystemLibrary.quit_editor()
