param(
 [string]$ApiKeyPath='C:\Users\greg_\OneDrive\Documents\line boss\linebosskey.txt',
 [string]$SourceRoot='C:\Users\greg_\Projects\LineBossCarFactory_Unreal 5.8\SourceAssets\Candidate\PressTrains\Shared\MeshyIsolatedIntake_v625\Prepared\Meshy6Views_v645',
 [string]$OutputRoot='C:\Users\greg_\Projects\LineBossCarFactory_Unreal 5.8\SourceAssets\Candidate\PressTrains\Shared\MeshyIsolatedIntake_v625\Generated\Meshy6_v646',
 [int]$PollSeconds=10,[int]$TimeoutMinutes=45
)
$ErrorActionPreference='Stop';$views=@('front','rear','left','right');$apiKey=(Get-Content $ApiKeyPath -Raw).Trim();if([string]::IsNullOrWhiteSpace($apiKey)){throw 'Empty Meshy key'};$headers=@{Authorization="Bearer $apiKey"}
$assets=Get-ChildItem $SourceRoot -Directory|Sort-Object Name;if($assets.Count-ne 11){throw "Expected 11 source folders, found $($assets.Count)"};New-Item -ItemType Directory -Path $OutputRoot -Force|Out-Null
function DataUri([string]$p){'data:image/png;base64,'+[Convert]::ToBase64String([IO.File]::ReadAllBytes($p))}
$before=(Invoke-RestMethod 'https://api.meshy.ai/openapi/v1/balance' -Headers $headers).balance;$required=30*$assets.Count;if($before-lt$required){throw "Need $required credits; balance $before"};$jobs=@()
foreach($asset in $assets){$out=Join-Path $OutputRoot $asset.Name;$orig=Join-Path $out 'Original';New-Item -ItemType Directory -Path $orig -Force|Out-Null;$uris=@();$sources=@();foreach($v in $views){$p=Join-Path $asset.FullName ($v+'.png');if(-not(Test-Path $p)){throw "Missing $p"};Copy-Item $p (Join-Path $orig ($v+'.png')) -Force;$uris+=DataUri $p;$sources+=@{view=$v;file=$p;sha256=(Get-FileHash $p -Algorithm SHA256).Hash}};$submission=Join-Path $out 'submission.json';if(Test-Path $submission){$taskId=(Get-Content $submission -Raw|ConvertFrom-Json).task_id}else{$payload=@{image_urls=$uris;ai_model='meshy-6';should_texture=$true;enable_pbr=$true;texture_resolution='2k';should_remesh=$false;image_enhancement=$false;remove_lighting=$true;target_formats=@('glb','fbx')};$created=Invoke-RestMethod 'https://api.meshy.ai/openapi/v1/multi-image-to-3d' -Headers $headers -Method Post -ContentType 'application/json' -Body ($payload|ConvertTo-Json -Depth 5 -Compress);$taskId=$created.result;@{asset=$asset.Name;task_id=$taskId;submitted_utc=(Get-Date).ToUniversalTime().ToString('o');expected_credits=30;sources=$sources;settings=@{ai_model='meshy-6';textured=$true;pbr=$true;resolution='2k';remesh=$false}}|ConvertTo-Json -Depth 8|Set-Content $submission -Encoding UTF8};$jobs+=@{asset=$asset.Name;task_id=$taskId;output=$out;status='SUBMITTED'};Write-Output "TRACKING $($asset.Name) $taskId"}
$deadline=(Get-Date).AddMinutes($TimeoutMinutes)
while((Get-Date)-lt$deadline){$pending=0;foreach($j in $jobs){if($j.status-in@('SUCCEEDED','FAILED','CANCELED')){continue};$task=Invoke-RestMethod ('https://api.meshy.ai/openapi/v1/multi-image-to-3d/'+$j.task_id) -Headers $headers;$j.status=$task.status;$task|ConvertTo-Json -Depth 12|Set-Content (Join-Path $j.output 'task_latest.json') -Encoding UTF8;if($task.status-eq'SUCCEEDED'){if($task.model_urls.glb){Invoke-WebRequest $task.model_urls.glb -OutFile (Join-Path $j.output ($j.asset+'_Meshy6_Raw.glb'))};if($task.model_urls.fbx){Invoke-WebRequest $task.model_urls.fbx -OutFile (Join-Path $j.output ($j.asset+'_Meshy6_Raw.fbx'))};$task|ConvertTo-Json -Depth 12|Set-Content (Join-Path $j.output 'task_complete.json') -Encoding UTF8;Write-Output "SUCCEEDED $($j.asset) credits=$($task.consumed_credits)"}elseif($task.status-in@('FAILED','CANCELED')){Write-Output "FAILED $($j.asset) $($task.status)"}else{$pending++}};if($pending-eq0){break};Start-Sleep $PollSeconds}
$after=(Invoke-RestMethod 'https://api.meshy.ai/openapi/v1/balance' -Headers $headers).balance;$summary=@{revision='v646';balance_before=$before;balance_after=$after;consumed=$before-$after;status=if(($jobs|Where-Object{$_.status-ne'SUCCEEDED'}).Count-eq0){'ALL_SUCCEEDED'}else{'INCOMPLETE'};jobs=$jobs};$summary|ConvertTo-Json -Depth 8|Set-Content (Join-Path $OutputRoot 'BATCH_SUMMARY_v646.json') -Encoding UTF8;$summary|ConvertTo-Json -Depth 8;if($summary.status-ne'ALL_SUCCEEDED'){exit 2}
