"""Record inspected v354/v356/v357 decisions without mutating assets."""
import hashlib,json
from datetime import datetime,timezone
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/"Saved/Audits/PressShopIntegration/press_shop_expanded_train_pitch_visual_decision_v358.json"
if OUT.exists():raise RuntimeError(f"Refusing to overwrite {OUT}")
files=[ROOT/"Saved/ValidationScreenshots/PressShopIntegration/v355_train_a_pro_detail/operator_oblique.png",ROOT/"Saved/ValidationScreenshots/PressShopIntegration/v355_train_a_pro_detail/full_broadside.png",ROOT/"Saved/ValidationScreenshots/PressShopIntegration/v357_expanded_train_pitch/overview.png",ROOT/"Saved/ValidationScreenshots/PressShopIntegration/v357_expanded_train_pitch/aisle_ab.png"]
evidence={str(p.relative_to(ROOT)).replace("\\","/"):hashlib.sha256(p.read_bytes()).hexdigest().upper() for p in files}
payload={"$schema":"cairnwell/audit/press-shop-expanded-train-pitch-visual-decision-v358/v1","generated_utc":datetime.now(timezone.utc).isoformat(),"status":"RETAIN_22M_TRAIN_PITCH_DIRECTION__V354_MACHINE_INTAKE_RETAINED__RELEASE_AND_PROMOTION_GATES_OPEN","decisions":{"v354_pro_detail_machine":"RETAIN_ISOLATED_INHERITED_HALL_DIRECTION__NOT_PROMOTED","v355_operator_oblique":"REJECT_RELEASE_COMPOSITION__TOO_CLOSE_OBLIQUE_AND_COLUMN_OBSTRUCTED","v355_full_broadside":"REJECT_RELEASE_COMPOSITION__FISHEYE_AND_COLUMN_OBSTRUCTED","v356_22m_layout":"RETAIN_LAYOUT_DIRECTION__843_5CM_ADJACENT_CLEAR_GAP__NOT_PROMOTED","v357_overview":"REJECT_CAMERA__ABOVE_ROOF","v357_aisle_ab":"PASS_PROVISIONAL_SPACING_READABILITY__PLAYER_HEIGHT__COLUMN_AND_ROUTE_GATES_OPEN"},"evidence":evidence,"measured":{"centre_pitch_cm":2200.0,"completed_visual_width_cm":1356.5000057220477,"adjacent_clear_gap_cm":843.4999942779523},"release_holds":["exact rebuilt navigation and collision regression after moving B-D","die-cart and service-bin turning/removal envelopes","credible structural-column and long-span roof solution marked TBC","Train B/C/D separate identity signs and material instances","fixed-camera four-line overview from inside shell","separate movable-module mapping and runtime regression","surface and lighting release polish"],"exterior_shell_enlargement":"NOT_YET_REQUIRED__EXISTING_FLOOR_CONTAINS_22M_CENTRES","replacement_authorized":False,"promotion_authorized":False}
OUT.parent.mkdir(parents=True,exist_ok=True);OUT.write_text(json.dumps(payload,indent=2)+"\n",encoding="utf-8");print(json.dumps(payload,indent=2))
